version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "${PORT}:5000"
    environment:
      FLASK_ENV: development
      JIRA_CLIENT_ID: ${JIRA_CLIENT_ID}
      JIRA_CLIENT_SECRET: ${JIRA_CLIENT_SECRET}
      JIRA_REDIRECT_URI: http://${HOST_NAME}:${PORT}/oauth/callback/jira
      JIRA_CLOUD_NAME: ${JIRA_CLOUD_NAME}
      HOST_NAME: ${HOST_NAME}
      PORT: ${PORT}
