version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    environment:
      FLASK_ENV: development
      JIRA_CLIENT_ID: ${JIRA_CLIENT_ID}
      JIRA_CLIENT_SECRET: ${JIRA_CLIENT_SECRET}
      JIRA_REDIRECT_URI: http://${HOST_NAME}:${PORT}/oauth/callback/jira
      JIRA_CLOUD_NAME: ${JIRA_CLOUD_NAME}
      HOST_NAME: ${HOST_NAME}
      PORT: ${PORT}
      
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certbot/data:/var/lib/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./certbot/data:/var/lib/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    command: certonly --webroot --webroot-path=/var/www/certbot --email your-email@example.com --agree-tos --no-eff-email -d yourdomain.com -d www.yourdomain.com --deploy-hook "nginx -s reload"

volumes:
  certbot: